// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftDrinkDataAccess.Database;

namespace SoftDrinkDataAccess.Migrations
{
    [DbContext(typeof(SoftDrinkDbContext))]
    partial class SoftDrinkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SoftDrinkDataAccess.Database.SoftDrinkPersonTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnName("NAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CORE_SOFT_DRINK_PERSON");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Toti"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Leo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Zerroni"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
